// @ts-check
// Barra lateral do curso. Por enquanto autogerada a partir da pasta docs/.
// Quando os módulos existirem, a ordem das lições será definida aqui.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cursoSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
